### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kidonng** [kidonng/pixiv-collection#2]
- [x] Fix resume not working for multiple page gallery
- [x] Fix `now dev`
- [x] Adjust margin/layout on large screens

---

- [x] Update pixiv API to [v2](https://api.imjad.cn/pixiv_v2.md)
- [x] Support link & selecting page indexes
  - [x] Use real page number instead of index
- [x] ~~Complete get image size API~~ Make a wrapper for pixiv API
- [x] ~~Redesign caption~~ Show illustration info
- [x] View illustrator info
  - [ ] Favorite illustrator
- [ ] Persists illustration/illustrator order
- [ ] Waterfall mode
